name: Build Documentation

on: [push]

jobs:

  build-documentation:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Pull render image
      run: docker pull stephenvertex/pandoc-ubuntu:latest

    - name: Run render
      run: docker run -it --rm -v `pwd`:/wdir --workdir /wdir pandoc-ubuntu:latest ./render.sh

    - uses: actions/upload-artifact@v1
      with:
        name: documentation
        path: out/report.pdf
